"""Theme palettes and glass-tuning dials.

Each theme is a dict of colors + glass rendering parameters. Non-Matrix
themes get the full glass-stacking pass (see spec section 4c); Matrix
explicitly opts out to preserve its phosphor-on-black aesthetic.
"""

THEMES = {
    "obsidian": {
        "name": "Obsidian",
        "bg": "#0d0d0d",
        "glass": "#1c1c1c",
        "glass_on_mica": "#1a1a1c",
        "title_bg": "#161616",
        "border": "#333333",
        "text": "#e8e4dc",
        "text_secondary": "#b8b4ac",
        "text_dim": "#777777",
        "text_muted": "#555555",
        "accent": "#6c63ff",
        "bar_bg": "#2a2a2a",
        "footer_bg": "#111111",
        "pace_marker": "#ff6b6b",
        "sparkline": "#6c63ff",
        "glass_alpha": 0.85,
        "border_alpha": 0.30,
        "border_tint": None,
        "accent_bloom": {"blur": 4, "alpha": 0.35},
        "inner_highlight": None,
    },
    "aurora": {
        "name": "Aurora",
        "bg": "#0a0f1a",
        "glass": "#161e30",
        "glass_on_mica": "#141d2e",
        "title_bg": "#0f172a",
        "border": "#334155",
        "text": "#e2e8f0",
        "text_secondary": "#94a3b8",
        "text_dim": "#64748b",
        "text_muted": "#475569",
        "accent": "#38bdf8",
        "bar_bg": "#1e293b",
        "footer_bg": "#0c1220",
        "pace_marker": "#f472b6",
        "sparkline": "#38bdf8",
        "glass_alpha": 0.80,
        "border_alpha": 0.50,
        "border_tint": "#38bdf8",
        "accent_bloom": {"blur": 6, "alpha": 0.55},
        "inner_highlight": {"color": "#38bdf8", "alpha": 0.20},
    },
    "ember": {
        "name": "Ember",
        "bg": "#1a0a0a",
        "glass": "#261414",
        "glass_on_mica": "#211010",
        "title_bg": "#1f0e0e",
        "border": "#442222",
        "text": "#f5e6e0",
        "text_secondary": "#d4a89c",
        "text_dim": "#8b6b60",
        "text_muted": "#6b4b40",
        "accent": "#f97316",
        "bar_bg": "#2d1a1a",
        "footer_bg": "#150808",
        "pace_marker": "#fbbf24",
        "sparkline": "#f97316",
        "glass_alpha": 0.82,
        "border_alpha": 0.40,
        "border_tint": "#f97316",
        "accent_bloom": {"blur": 6, "alpha": 0.55},
        "inner_highlight": {"color": "#f97316", "alpha": 0.18},
    },
    "mint": {
        "name": "Mint",
        "bg": "#0a1a14",
        "glass": "#122a1e",
        "glass_on_mica": "#0e2419",
        "title_bg": "#0c1f14",
        "border": "#22543d",
        "text": "#e0f5ec",
        "text_secondary": "#9cd4b8",
        "text_dim": "#5a9a78",
        "text_muted": "#3a7a58",
        "accent": "#34d399",
        "bar_bg": "#163020",
        "footer_bg": "#081510",
        "pace_marker": "#f472b6",
        "sparkline": "#34d399",
        "glass_alpha": 0.78,
        "border_alpha": 0.45,
        "border_tint": "#34d399",
        "accent_bloom": {"blur": 4, "alpha": 0.35},
        "inner_highlight": {"color": "#34d399", "alpha": 0.22},
    },
    "matrix": {
        "name": "Matrix",
        "bg": "#020a02",
        "glass": "#0a140a",
        "glass_on_mica": "#0a140a",
        "title_bg": "#040d04",
        "border": "#0f2a0f",
        "text": "#00ff41",
        "text_secondary": "#00cc33",
        "text_dim": "#00802b",
        "text_muted": "#005a1e",
        "accent": "#00ff41",
        "bar_bg": "#0a1a0a",
        "footer_bg": "#020802",
        "pace_marker": "#ff0040",
        "sparkline": "#00ff41",
        "glass_alpha": 1.0,
        "border_alpha": 0.50,
        "border_tint": "#00ff41",
        "accent_bloom": {"blur": 4, "alpha": 0.60},
        "inner_highlight": None,
        "opts_out_of_mica": True,
        "monospace_font": "Cascadia Code",
        "monospace_fallback": "Consolas",
        "card_corner_radius": 2,
    },
}


def usage_color(pct: int) -> str:
    """Return the bar fill color for a given utilization %."""
    if pct < 50:
        return "#4ade80"
    if pct < 75:
        return "#facc15"
    if pct < 90:
        return "#fb923c"
    return "#f87171"
